# use_frameworks!
platform :ios, '8.0'

target 'KFXAbstracts_Example' do
  pod 'KFXAbstracts', :path => '../'

  # Pods for Main target
  pod 'KFXAdditions'

  target 'KFXAbstracts_Tests' do
    inherit! :search_paths

    
  end
end
