platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true

target 'KFXAbstracts_Example' do
  pod 'KFXAbstracts', :path => '../'

	### If using from trunk
	source 'https://cdn.cocoapods.org/'
  pod 'KFXAdditions'

  target 'KFXAbstracts_Tests' do
    inherit! :search_paths

    
  end
end
